**IMPORTING DATASET OF AIRLINE TWEETS WITH 3 CATEGORIES POSITIVE,NEGATIVE,NEUTRAL**

In [113]:
import pandas as pd
data = pd.read_csv("Tweets.csv")
data.head()
data['airline'].value_counts()

United            3822
US Airways        2913
American          2759
Southwest         2420
Delta             2222
Virgin America     504
Name: airline, dtype: int64

**SELECTING SPECIFIC COLUMN FROM DATASET**

In [0]:
 data = data[['text','airline_sentiment']]

In [115]:
data.head()

text airline_sentiment
0                @VirginAmerica What @dhepburn said.           neutral
1  @VirginAmerica plus you've added commercials t...          positive
2  @VirginAmerica I didn't today... Must mean I n...           neutral
3  @VirginAmerica it's really aggressive to blast...          negative
4  @VirginAmerica and it's a really big bad thing...          negative

In [116]:
data['airline_sentiment'].unique()

array(['neutral', 'positive', 'negative'], dtype=object)

In [117]:
data['airline_sentiment'].value_counts()

negative    9178
neutral     3099
positive    2363
Name: airline_sentiment, dtype: int64

**LABEL_ENCODING DEPENDENT COULMN**

\



In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['airline_sentiment'] = le.fit_transform(data['airline_sentiment'])

In [119]:
data.head()

text  airline_sentiment
0                @VirginAmerica What @dhepburn said.                  1
1  @VirginAmerica plus you've added commercials t...                  2
2  @VirginAmerica I didn't today... Must mean I n...                  1
3  @VirginAmerica it's really aggressive to blast...                  0
4  @VirginAmerica and it's a really big bad thing...                  0

In [120]:
X = data['text']
y = data['airline_sentiment']
print(data.head())


                                                text  airline_sentiment
0                @VirginAmerica What @dhepburn said.                  1
1  @VirginAmerica plus you've added commercials t...                  2
2  @VirginAmerica I didn't today... Must mean I n...                  1
3  @VirginAmerica it's really aggressive to blast...                  0
4  @VirginAmerica and it's a really big bad thing...                  0


In [121]:
data.shape

(14640, 2)

**REMOVING COMMON  WORDS I.E STOP WORDS**

**REMOVING PUNCTUATION MARKS**

**CONVERTING STRING TO LOWER CASE **

In [0]:
import spacy
nlp = spacy.load('en')
nlp.Defaults.stop_words.add("virginamerica")
nlp.Defaults.stop_words.add("united")
nlp.Defaults.stop_words.add("unite")
nlp.Defaults.stop_words.add("delta")
nlp.Defaults.stop_words.add("southwest")
nlp.Defaults.stop_words.add("american")
nlp.Defaults.stop_words.add("us airways")




punctuations = '!"#$%&\'()*+,-/:;<=>?@[\\]^_`{|}~'
texts = []
for i in range(14640):
    rev=re.sub('[^a-zA-Z]',' ',X[i])
    rev=rev.lower();
    doc = nlp(rev, disable=['parser', 'ner'])
    tokens = [tok.lemma_.lower().strip() for tok in doc if tok.lemma_ != '-PRON-']
    tokens = [tok for tok in tokens if tok not in nlp.Defaults.stop_words and tok not in punctuations]
    tokens = ' '.join(tokens)
    texts.append(tokens)
f = pd.DataFrame(texts)


In [123]:
print(f.head())



#CHECKING FOR NULL VALUES
X.isnull().sum()

                                                   0
0                                           dhepburn
1            plus ve add commercial experience tacky
2                        didn t today mean need trip
3  s aggressive blast obnoxious entertainment gue...
4                                    s big bad thing


0

In [124]:
print(X.head(),y.head())

0                  @VirginAmerica What @dhepburn said.
1    @VirginAmerica plus you've added commercials t...
2    @VirginAmerica I didn't today... Must mean I n...
3    @VirginAmerica it's really aggressive to blast...
4    @VirginAmerica and it's a really big bad thing...
Name: text, dtype: object 0    1
1    2
2    1
3    0
4    0
Name: airline_sentiment, dtype: int64


In [0]:
X = f[0]

In [126]:

print(X.shape)
print(y.shape)


#CHECKING FOR NULL VALUES
print(X.isnull().sum())

(14640,)
(14640,)
0




1.   creating a pipeline to performs multiple functions ina single step 

2.   splitting training set and test set which will be used both for training and evaluation


3.   fitting linear SVC model to training set 






In [127]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
pl = Pipeline([('tfidf',TfidfVectorizer()),('clf',LinearSVC())])
pl.fit(x_train,y_train)



Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
               

**evaluating model using confusion matrix**

**classifiaction report**

**accuracy score**

In [132]:


predicts = pl.predict(x_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,predicts))
print(classification_report(y_test,predicts))
print(accuracy_score(y_test,predicts))

[[1668  149   53]
 [ 250  309   55]
 [  99   68  277]]
              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1870
           1       0.59      0.50      0.54       614
           2       0.72      0.62      0.67       444

    accuracy                           0.77      2928
   macro avg       0.71      0.67      0.69      2928
weighted avg       0.76      0.77      0.76      2928

0.769808743169399


**MODEL TRAINED IS 76% ACCURATE**